### ISSUE TITLE
Non english ASCII character are broken in downloaded files names

### ISSUE THREAD

**Issue by slrslr** [pkg-src/jdownloader2.snap#2]
Hello,

the snap has wrong locale set: sun.jnu.encoding=ANSI_X3.4-1968

set correct locale within the snap/launcher
see
https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1576411
https://forum.snapcraft.io/t/lack-of-compiled-locales-breaks-gettext-based-localisation/3758

without proper locale set within the snap package, every non asci character will be broken/replaced by ?

my snap: latest/stable:    0+git.1670793

**Comment by valkodev** [comment]
I have same issue. Other possible way to solve it, could be to run JDownloader with additional parameters:
java -Dsun.jnu.encoding=UTF-8 -Dfile.encoding=UTF-8 -jar JDownloader.jar 

Running the JDownloader with above command in terminal, encoding is proper and all works.

Issue also desribed here: https://board.jdownloader.org/showthread.php?t=67428

And I reported similar issue for dcoker image:
https://github.com/jaymoulin/docker-jdownloader/issues/83

snap --version
snap    2.48+20.04
snapd   2.48+20.04
series  16
ubuntu  20.04
kernel  5.4.0-56-generic

**Comment by fnkr** [comment]
I pushed a fix for this to the candidate channel. Please test and let me know if this works for you.

```
snap refresh jdownloader2 --channel=latest/candidate
```

**Comment by valkodev** [comment]
Thanks for quick support. Unfortunatelly this is not working. I see you passing proper arguments into VM but the sun.jnu.encoding is still wrong. See below from the log. Probably setting locales is still needed.

file.encoding=UTF-8
sun.jnu.encoding=ANSI_X3.4-1968
sun.io.unicode.encoding=UnicodeLittle
VMArgs: [-Dsun.jnu.encoding=UTF-8, -Dfile.encoding=UTF-8]

**Comment by fnkr** [comment]
I pushed another change to the candidate channel. Can you please try again?

```
snap refresh jdownloader2 --channel=latest/candidate
```

**Comment by slrslr** [comment]
@fnkr hello, i have just tried and the downloaded file name still contain question marks. [Details here](https://bin.disroot.org/?efbb56c22b167cac#B6iVKqFrchnQUXvSPKR2Tq6eEyd9radNfFFApQKCVzgu).

**Comment by samasaki** [comment]
@fnkr hello, the problem can be fixed by adding gnome-3-38 extension like:

apps:
 jdownloader:
  extensions:
   - gnome-3-38
